language: csharp
sudo: required
dist: xenial

dotnet: 2.2
mono:
  - 5.14.0
  - latest # => "stable release"
  - alpha
  - beta
  - weekly # => "latest commits"
os:
  - linux

script:
  - travis_wait ./build.sh

matrix:
  fast_finish: true
  allow_failures:
    - mono: latest
    - mono: alpha
    - mono: beta
    - mono: weekly

global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
